### ISSUE TITLE
1st Release Pending Tasks

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#42]
> **WIP WARNING** — This list of pending tasks is still incomplete and will be constantly updated to mirror the current progress status and until the project reaches its first tagged release.

We're heading toward [<kbd>1st Release</kbd>] of the project and need to wrap up all pending tasks before merging into master branch.

- project boards: [<kbd>Porting</kbd>]&nbsp;&nbsp;[<kbd>1st Release</kbd>]

The task list below presents [all relevant open Issues] in a meaningful order, with comments, as well as introducing new tasks for which there is no separate Issue, and **will be constantly updated** to mirror the current progress status.

This will be the last standing open Issue for the [<kbd>1st Release</kbd>] project, and shall be closed when the book is publicly released.

### Blocking Issues

The following Issues are awaiting for @tessman approval [<kbd>:clock2: pending approval</kbd>] before they can be fully integrated in the project and closed:

- [x] __Book Metadata__ (Issue #51) — needs checking if the info is OK.
- [x] __§7.1 & Ch17: Add Cross-References to Dynamic Grammars__ (Issue #48).
- [x] __B.7: Missing Word in Hugo Lib Definition__ (Issue #47).
- [x] __Conflicting Legal Information (Book vs BSD-2)__ (Issue #2) — WIP, just need confirmation it's OK once ready.
- [x] __§9.2: Code Errors in Strings__ (Issue #38).
- [x] __Ch 12: Adapt Syntax Definitions__ (Issue #36).
- [x] __§10.6: Hard to Read Sentence__ (Issue #30) — optional, sentence improvment.

### Pending Tasks

- [x] **UNRESOLVED QUESTIONS**
    + [x] __Release Version Scheme__ (Issue #31) — still need to decide how to handle updates using a scheme able to distinguish between changes to actual contents vs presentation and styles, and between changes to backend-specific templates vs AsciiDoc sources.
- [x] **BOOK CONTENTS, FORMATTING & STYLES**
    + [x] __Porting Stage: Final Tasks__ (Issue #46) — last minute checks to ensure the AsciiDoc porting stage is definitely over.
    + [x] __[Colophon]__:
        * [x] Needs some custom CSS styles for better formatting.
        * [x] Original pubblication data like ISBN might need to be contextualized as being for historical reference (for it does't apply to this digital edition).
    + [x] __Books Alt-Titles__ — the "OR ..." part that follows the main Book title requires custom styles/roles to enlarge the font face and size so it's similar to the main title but slight smaller, possibly with a different color but not black:
        * [x] Add `[.text-center.big.ortitle]` and customize CSS:
            - [x] __Book I__ — "or _How to Write Games and Influence People_"
            - [x] __Book II__ — "or _Under the Hood of Hugo and the .HEX File Format_"
        * [x] Document this custom style either in `docs_src/README.md` or in `CONVENTIONS.md`
    + [x] __Captions__ — we should take advantage of Asciidoctor features for handling captions in figures and tables. Although the HTML backend doesn't provide an automatically generated list of all the book figures and tables, other backends do (or might), and it might be possible to find or create an extension to do it in HTML too. Besides, captions aid the reading experience and provide auto-generated anchor IDs for direct linking to the figure/table.
        * [x] __Tables Captions__ — not every AsciiDoc table in the book is a table in the true sense, i.e. some tables are being used just to provide better formatting of some contents, but not qualify as a table in respect to the original document.
            - §2.3: _Table 1. List of Hugo Data Types_ (`table-hugo-data-types`)
            - §4.1: _Table 2. Predefined Global Variables_ (`table-engine-variables`)
            - §4.3: _Table 3. Standard Colors Defined by the Hugo Library_ (`table-hugolib-colors`)
            - §8.1: _Table 4. Predefined Global Variables and Properties_ (`table-engine-globals`)
            - §8.3: _Table 5. Default ParseError Responses_ (`table-parseerror-responses`)
            - §14.1: _Table 6. Memory Map of a .HEX File_ (`table-hex-file-map`)
            - §14.2: _Table 7. Memory Map of a .HEX File Header_ (`table-hex-file-header-map`)
            - §27.2: _Table 8. Memory Map of a .HDX File_ (`table-hdx-file-map`)
        * [x] __Figures Captions__:
            - §25: _Figure 1. Flowchart of the Hugo Compiler_ (`fig-compiler-flowchart`)
            - §26: _Figure 2. Flowchart of the Hugo Engine_ (`fig-engine-flowchart`)
            - §27: _Figure 3. Flowchart of the Hugo Debugger_ (`fig-debugger-flowchart`)
- [x] **PROJECT DOCUMENTATION**
[<kbd>:books: documentation</kbd>]
    + [x]  [`CHANGES.md`][CHANGES.md]:
        * [x]  __Document Contents Changes__ (Issue #11).
    + [x]  [`README.md`][README.md]:
        * [x]  Polish document for public release.
    + [x]  [`docs_src/README.md`][docs_src/README.md]:
        * [x]  Move all TODOs to Issues.
        * [x]  Polish document for public release.
- [x] **GITHUB PAGES WEBSITE** — The book will also be available for online reading via GitHub Pages. This requires a two-steps setup, the last one being handled after merging into `master` (Issue #44):
[<kbd>GitHub Pages</kbd>]&nbsp;&nbsp;[<kbd>:hammer: GitHub Pages</kbd>]
    + [x] __Move HTML Book to "docs/" for GitHub Pages Setup__ (Issue #43).
    + [x] __Rename HTML File in "docs/" Folder__ (Issue #49).
- [x] **PRE-MERGE CHORES** — things to be done right before merging into `master` branch, mostly related URL changes resulting from branch switching.
[<kbd>:clock2: on 1st release</kbd>]
    + [x] __Fix Live HTML Links__ (Issue #9).
    + [x] __Fix Travis CI Badge URL__ (Issue #8).
    + [x] __Publish Book on WWW via GitHub Pages__ (Issue #44).
    + [x] __Post-Merge Chores__ (Issue #52).

[all relevant open Issues]: ../issues?utf8=✓&q=is%3Aopen+project%3Atajmone%2Fhugo-book%2F1+project%3Atajmone%2Fhugo-book%2F2 "Filter all open Issues belonging to 'Porting' and '1st release' projects"

[<kbd>1st Release</kbd>]: ../projects/2 "project: 1st Release"
[<kbd>Porting</kbd>]: ../projects/1 "project: Porting"

[<kbd>GitHub Pages</kbd>]: ../milestone/8 "milestone: GitHub Pages"

[<kbd>:clock2: on 1st release</kbd>]: ../labels/%3Aclock2%3A%20on%201st%20release "label: on 1st release"

[<kbd>:books: documentation</kbd>]: ../issues?q=is%3Aopen+label%3A"%3Abooks%3A+documentation"+project%3Atajmone%2Fhugo-book%2F2 "label: documentation"

[<kbd>:clock2: pending approval</kbd>]: ../issues?q=is%3Aissue+is%3Aopen+label%3A"%3Aclock2%3A+pending+approval"
"label: pending approval"

[<kbd>:hammer: GitHub Pages</kbd>]: ../labels/%3Ahammer%3A%20GitHub%20Pages "label: GitHub Pages"

[CHANGES.md]: ../blob/draft/CHANGES.md
[README.md]: ../blob/draft/README.md
[docs_src/README.md]: ../blob/draft/docs_src/README.md

[Colophon]: https://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/hugo-book.html#colophon
