### ISSUE TITLE
Update Changelog for v1.1.0

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#69]
Before merging release v1.1.0, update tha Changelog section in the main README.

The changes of the following Issues and commits between the previous release and the upcoming one need to be documented:

- [ ] #55
- [ ] #56
- [ ] #61
- [ ] #63
- [ ] #64 — Adds 2 new footnotes in App B.2.
- [ ] #65
- [x] #72 — Fix images previews in coalesced book.

This Issues and commits concern minor changes that might not be worth documenting at all (maybe just provide a quick link to the Issue), so let's keep them in a separate list, as a reminder, until a decision is made:

- [ ] #60 — removes the 2nd space in `array <arrayname> [<array size>]`.
- [ ] affdf3d — Minor fixes to App. H formatting.

Some of the above Issues are already closed and dealt with. I've postponed updating the Changelog because I haven't yet decided how detailed it should be — whether I should just group the changes into macro categories like "Typos", "Code Fixes", etc., and just link to the various Issues, or whether I should cover the details.

I won't be able to decide until I have the big picture of all the changes that made it through to v1.1.0.
